# Generated by Django 3.2.5 on 2021-10-16 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('tags', models.CharField(max_length=1024)),
                ('developers', models.ManyToManyField(related_name='developers', to=settings.AUTH_USER_MODEL)),
                ('manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(projects.models.TimeStamps, models.Model),
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_type', models.CharField(choices=[('bug', 'Bug'), ('query', 'Query')], default='bug', max_length=20)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=1024)),
                ('bug_priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('NA', 'Not Applicable'), ('enhancement', 'Enhancement')], default='low', max_length=20)),
                ('closed', models.BooleanField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(projects.models.TimeStamps, models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=1024)),
                ('author_role', models.CharField(choices=[('contributor', 'Contributor'), ('developer', 'Developer'), ('project_manager', 'Project Manager')], default='contributor', max_length=20)),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.thread')),
            ],
            bases=(projects.models.TimeStamps, models.Model),
        ),
    ]
